name: Build and Test Otlichnik

on: [push, pull_request]

jobs:
  build:
    defaults:
      run:
        working-directory: otlichnik/

    strategy:
      matrix:
        python-version: ["3.9", "3.10"]
        platform: [ubuntu-22.04, windows-2022, macos-11]

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r dev-requirements.txt
          pip install -e .
      - name: Test with pytest
        run: |
          pytest